/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    produtos: Produto;
    categorias: Categoria;
    solucoes: Solucao;
    projetos: Projeto;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    solucoes: SolucoesSelect<false> | SolucoesSelect<true>;
    projetos: ProjetosSelect<false> | ProjetosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  nome: string;
  /**
   * Gerado a partir de "nome". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  categoria: number | Categoria;
  /**
   * Fabricante da peça. A faixa de marcas da home é uma lista à parte, editada em Home.
   */
  marca?: string | null;
  /**
   * Uma ou duas linhas. É o que aparece no card do catálogo.
   */
  descricao?: string | null;
  /**
   * Em reais. Deixe vazio para exibir "sob consulta".
   */
  preco?: number | null;
  /**
   * Aparece no card e abre a galeria na página do produto.
   */
  imagem?: (number | null) | Media;
  /**
   * Fotos adicionais mostradas na página do produto.
   */
  galeria?: (number | Media)[] | null;
  /**
   * Texto longo da página do produto. Aceita listas, negrito e links.
   */
  detalhes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pares como Material / Madeira maciça. Viram a tabela da página do produto.
   */
  especificacoes?:
    | {
        rotulo: string;
        valor: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Termos alternativos que ajudam o cliente a achar o produto na busca.
   */
  tags?:
    | {
        valor: string;
        id?: string | null;
      }[]
    | null;
  destaque?: boolean | null;
  /**
   * Desmarque para tirar do catálogo sem apagar o cadastro.
   */
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nome: string;
  /**
   * Gerado a partir de "nome". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  descricao?: string | null;
  /**
   * Define a ordem de exibição no catálogo. Menor aparece primeiro.
   */
  ordem?: number | null;
  /**
   * A home ganha uma seção para cada categoria marcada aqui.
   */
  destacarNaHome?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreve a imagem para leitores de tela e para quando ela não carregar.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Soluções oferecidas, exibidas na página /solucoes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solucoes".
 */
export interface Solucao {
  id: number;
  titulo: string;
  /**
   * Gerado a partir de "titulo". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  /**
   * Uma ou duas linhas: que problema do ambiente essa solução resolve.
   */
  resumo?: string | null;
  /**
   * Texto longo: como funciona na prática.
   */
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Lista objetiva do que o cliente recebe. Aparece ao lado do texto.
   */
  entregaveis?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional. Sem imagem, o bloco usa só o número e o texto.
   */
  imagem?: (number | null) | Media;
  /**
   * Define a numeração e a sequência na página. Menor aparece primeiro.
   */
  ordem?: number | null;
  /**
   * Desmarque para tirar de /solucoes sem apagar o cadastro.
   */
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Projetos executados, exibidos na página /trabalhos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos".
 */
export interface Projeto {
  id: number;
  titulo: string;
  /**
   * Gerado a partir de "titulo". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  /**
   * Bairro, cidade — ex.: Meireles, Fortaleza.
   */
  local?: string | null;
  ano?: number | null;
  tipo?: ('residencial' | 'comercial' | 'corporativo') | null;
  /**
   * Uma ou duas linhas sobre o que foi resolvido no ambiente.
   */
  resumo?: string | null;
  /**
   * Foto principal do ambiente pronto.
   */
  capa?: (number | null) | Media;
  /**
   * Outros ângulos do mesmo trabalho.
   */
  galeria?: (number | Media)[] | null;
  /**
   * Texto longo: o desafio do espaço e a solução adotada.
   */
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Liga o trabalho ao catálogo — o visitante vê o que foi usado.
   */
  produtos?: (number | Produto)[] | null;
  /**
   * Menor aparece primeiro. Empates caem para o ano mais recente.
   */
  ordem?: number | null;
  /**
   * Aparece na prévia da home.
   */
  destaque?: boolean | null;
  /**
   * Desmarque para tirar de /trabalhos sem apagar o cadastro.
   */
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'solucoes';
        value: number | Solucao;
      } | null)
    | ({
        relationTo: 'projetos';
        value: number | Projeto;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  categoria?: T;
  marca?: T;
  descricao?: T;
  preco?: T;
  imagem?: T;
  galeria?: T;
  detalhes?: T;
  especificacoes?:
    | T
    | {
        rotulo?: T;
        valor?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        valor?: T;
        id?: T;
      };
  destaque?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  descricao?: T;
  ordem?: T;
  destacarNaHome?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "solucoes_select".
 */
export interface SolucoesSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  resumo?: T;
  descricao?: T;
  entregaveis?:
    | T
    | {
        item?: T;
        id?: T;
      };
  imagem?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos_select".
 */
export interface ProjetosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  local?: T;
  ano?: T;
  tipo?: T;
  resumo?: T;
  capa?: T;
  galeria?: T;
  descricao?: T;
  produtos?: T;
  ordem?: T;
  destaque?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Linha curta acima do título. Posiciona antes de o visitante ler o resto.
   */
  chapeu?: string | null;
  titulo: string;
  subtitulo?: string | null;
  ctaTexto: string;
  ctaLink: string;
  ctaSecundarioTexto?: string | null;
  /**
   * Deixe o texto vazio para esconder o botão.
   */
  ctaSecundarioLink?: string | null;
  /**
   * Opcional. Sem imagem, o hero usa um fundo sólido.
   */
  imagem?: (number | null) | Media;
  /**
   * Lista fixa exibida na faixa rolante da home, na ordem em que estiverem aqui. Deixe vazio para esconder a faixa.
   */
  marcas?:
    | {
        nome: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Bloco da home que leva para /trabalhos. Some se não houver trabalho publicado.
   */
  secaoTrabalhos?: {
    chapeu?: string | null;
    titulo?: string | null;
    texto?: string | null;
    ctaTexto?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  chapeu?: T;
  titulo?: T;
  subtitulo?: T;
  ctaTexto?: T;
  ctaLink?: T;
  ctaSecundarioTexto?: T;
  ctaSecundarioLink?: T;
  imagem?: T;
  marcas?:
    | T
    | {
        nome?: T;
        id?: T;
      };
  secaoTrabalhos?:
    | T
    | {
        chapeu?: T;
        titulo?: T;
        texto?: T;
        ctaTexto?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}