/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    produtos: Produto;
    categorias: Categoria;
    unidades: Unidade;
    projetos: Projeto;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    produtos: ProdutosSelect<false> | ProdutosSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    unidades: UnidadesSelect<false> | UnidadesSelect<true>;
    projetos: ProjetosSelect<false> | ProjetosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    sobre: Sobre;
    localizacao: Localizacao;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    sobre: SobreSelect<false> | SobreSelect<true>;
    localizacao: LocalizacaoSelect<false> | LocalizacaoSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos".
 */
export interface Produto {
  id: number;
  nome: string;
  /**
   * Gerado a partir de "nome". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  categoria: number | Categoria;
  /**
   * Fabricante da peça, como Kingspan ou Wallboard. Aparece na página do produto.
   */
  marca?: string | null;
  /**
   * Um parágrafo curto na página do produto, logo abaixo do nome. Também entra na busca do catálogo.
   */
  descricao?: string | null;
  /**
   * Em reais. Aparece só na página do produto — o card do catálogo sempre mostra "Sob orçamento". Vazio, a página também mostra "Sob orçamento".
   */
  preco?: number | null;
  /**
   * A capa do produto: aparece no card do catálogo e é a primeira foto da galeria.
   */
  imagem?: (number | null) | Media;
  /**
   * Outros ângulos, detalhes e aplicações. Aparecem como miniaturas ao lado da foto principal, na ordem em que estiverem aqui — arraste para reordenar.
   */
  galeria?: (number | Media)[] | null;
  /**
   * Texto longo da página do produto. Aceita listas, negrito e links.
   */
  detalhes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Pares como Espessura / 30 mm. Viram a tabela da página do produto.
   */
  especificacoes?:
    | {
        rotulo: string;
        valor: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparecem como etiquetas na página do produto e ajudam a achá-lo na busca — vale incluir termos que o cliente usaria.
   */
  tags?:
    | {
        valor: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Produtos em promoção aparecem primeiro no catálogo, antes dos demais. Entre eles, a ordem continua alfabética.
   */
  promocao?: boolean | null;
  /**
   * Marque para o produto aparecer na seção "Produtos e serviços que a LM entrega", na home. Sem nenhum marcado, a seção mostra os mais recentes do catálogo.
   */
  destaque?: boolean | null;
  /**
   * Desmarque para tirar do catálogo sem apagar o cadastro.
   */
  ativo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nome: string;
  /**
   * Gerado a partir de "nome". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  /**
   * A frente da LM a que esta categoria pertence — é o que agrupa os produtos no filtro de unidades. Sem unidade, os produtos aparecem só em "Todas" e no filtro da própria categoria. Para criar uma unidade nova, use Unidades.
   */
  unidade?: (number | null) | Unidade;
  /**
   * Define a ordem de exibição no catálogo. Menor aparece primeiro.
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * As frentes da LM. Cada categoria pertence a uma unidade, e o site usa esta lista nos filtros, nos cards da home, na página do produto, no rodapé e no formulário de orçamento.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unidades".
 */
export interface Unidade {
  id: number;
  /**
   * Curto: é o texto do botão de filtro. Ex.: Esquadrias, Vidros, Construção.
   */
  nome: string;
  /**
   * Gerado a partir de "nome". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  /**
   * Uma linha sobre o que a unidade faz. Aparece no card de "Comece por unidade", na home, e no fim da página de cada produto.
   */
  descricao?: string | null;
  /**
   * A foto do card. Vertical funciona melhor — o card é mais alto que largo. Sem foto, o card usa uma imagem genérica do catálogo.
   */
  imagem?: (number | null) | Media;
  /**
   * Ordem em todos os lugares onde as unidades aparecem. Menor vem primeiro.
   */
  ordem?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Descreve a imagem para leitores de tela e para quando ela não carregar.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Obras entregues pela LM. Aparecem em "Projetos que mostram como trabalhamos", na página Sobre, e cada um ganha a sua própria página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos".
 */
export interface Projeto {
  id: number;
  titulo: string;
  /**
   * Gerado a partir de "titulo". Edite apenas se precisar de uma URL específica.
   */
  slug?: string | null;
  /**
   * Bairro, cidade — ex.: Centro, Seabra.
   */
  local?: string | null;
  ano?: number | null;
  tipo?: ('Residencial' | 'Comercial' | 'Corporativo') | null;
  /**
   * Uma ou duas linhas sobre o que foi resolvido no ambiente.
   */
  resumo?: string | null;
  /**
   * Foto principal do ambiente pronto.
   */
  capa?: (number | null) | Media;
  /**
   * Outros ângulos do mesmo trabalho.
   */
  galeria?: (number | Media)[] | null;
  /**
   * Texto longo: o desafio do espaço e a solução adotada.
   */
  descricao?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Liga o trabalho ao catálogo — o visitante vê o que foi usado.
   */
  produtos?: (number | Produto)[] | null;
  /**
   * Ordem na página Sobre. Menor aparece primeiro.
   */
  ordem?: number | null;
  /**
   * Desmarque para tirar do site sem apagar o cadastro.
   */
  publicado?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  nome?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'produtos';
        value: number | Produto;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'unidades';
        value: number | Unidade;
      } | null)
    | ({
        relationTo: 'projetos';
        value: number | Projeto;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "produtos_select".
 */
export interface ProdutosSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  categoria?: T;
  marca?: T;
  descricao?: T;
  preco?: T;
  imagem?: T;
  galeria?: T;
  detalhes?: T;
  especificacoes?:
    | T
    | {
        rotulo?: T;
        valor?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        valor?: T;
        id?: T;
      };
  promocao?: T;
  destaque?: T;
  ativo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  unidade?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unidades_select".
 */
export interface UnidadesSelect<T extends boolean = true> {
  nome?: T;
  slug?: T;
  descricao?: T;
  imagem?: T;
  ordem?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projetos_select".
 */
export interface ProjetosSelect<T extends boolean = true> {
  titulo?: T;
  slug?: T;
  local?: T;
  ano?: T;
  tipo?: T;
  resumo?: T;
  capa?: T;
  galeria?: T;
  descricao?: T;
  produtos?: T;
  ordem?: T;
  publicado?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  nome?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * A vitrine logo abaixo do topo. Os produtos vêm do catálogo: marque "Mostrar na home" em cada um. Sem nenhum marcado, aparecem os mais recentes.
   */
  secaoCatalogo?: {
    chapeu?: string | null;
    titulo?: string | null;
    texto?: string | null;
  };
  /**
   * Aparecem sobre a foto do topo: empilhados à direita no computador, e como um slide que desliza no celular. Todos com o mesmo tamanho. Deixe vazio para esconder.
   */
  bannersHero?:
    | {
        /**
         * PNG na proporção 16:6 — 1020 × 390 px atende bem do computador ao celular. Fora dessa proporção, as bordas da arte podem ser cortadas.
         */
        imagem: number | Media;
        /**
         * O que o banner diz, em uma frase. É o que quem usa leitor de tela ouve no lugar da imagem.
         */
        alt: string;
        /**
         * Para onde o banner leva: /catalogo, a página de um produto (/catalogo/telha-residence) ou /#orcamento. Vazio, o banner não vira clicável.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparece logo depois das categorias, antes do bloco "Três frentes, uma equipe". Dois banners por linha. Deixe vazio para esconder a faixa.
   */
  bannersFaixa1?:
    | {
        /**
         * PNG na proporção 8:3 — 1200 × 450 px funciona bem. Fora dessa proporção, as bordas da arte podem ser cortadas.
         */
        imagem: number | Media;
        /**
         * O que o banner diz, em uma frase. É o que quem usa leitor de tela ouve no lugar da imagem.
         */
        alt: string;
        /**
         * Para onde o banner leva: /catalogo, a página de um produto (/catalogo/telha-residence) ou /#orcamento. Vazio, o banner não vira clicável.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Aparece depois do bloco "Três passos até a instalação". Dois banners por linha. Deixe vazio para esconder a faixa.
   */
  bannersFaixa2?:
    | {
        /**
         * PNG na proporção 8:3 — 1200 × 450 px funciona bem. Fora dessa proporção, as bordas da arte podem ser cortadas.
         */
        imagem: number | Media;
        /**
         * O que o banner diz, em uma frase. É o que quem usa leitor de tela ouve no lugar da imagem.
         */
        alt: string;
        /**
         * Para onde o banner leva: /catalogo, a página de um produto (/catalogo/telha-residence) ou /#orcamento. Vazio, o banner não vira clicável.
         */
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página "Sobre" do site. As abas seguem a ordem das seções na página, e o que estiver vazio aqui simplesmente não aparece lá. Ainda faltam História e Equipe: enquanto estiverem vazias, essas duas seções ficam de fora.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sobre".
 */
export interface Sobre {
  id: number;
  /**
   * Linha curta acima do título.
   */
  chapeu?: string | null;
  titulo: string;
  lead?: string | null;
  /**
   * Botão logo abaixo do texto de abertura.
   */
  ctaTexto?: string | null;
  ctaLink?: string | null;
  /**
   * Opcional. Uma foto da equipe, do galpão ou de uma obra entregue.
   */
  imagem?: (number | null) | Media;
  /**
   * Etiqueta curta sobre a foto de abertura. Deixe vazio para esconder.
   */
  imagemLegenda?: string | null;
  /**
   * Os dados objetivos da LM, logo abaixo do título da página. Só as três primeiras linhas preenchidas aparecem — ponha no topo o que mais importa. Preencha só o que for verdade: linha sem valor é pulada.
   */
  ficha?:
    | {
        rotulo: string;
        valor?: string | null;
        id?: string | null;
      }[]
    | null;
  capacidadesChapeu?: string | null;
  capacidadesTitulo?: string | null;
  capacidadesTexto?: string | null;
  /**
   * O que a LM executa de ponta a ponta. Deixe vazio para esconder a seção.
   */
  capacidades?:
    | {
        titulo: string;
        texto?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * O cabeçalho da seção. Os projetos em si vêm da coleção Projetos — só os publicados aparecem, na ordem definida lá.
   */
  projetos?: {
    chapeu?: string | null;
    titulo?: string | null;
    ctaTexto?: string | null;
    ctaLink?: string | null;
  };
  /**
   * PENDENTE — como a LM começou: de onde veio, há quanto tempo está na estrada, o que mudou. Sem texto aqui, a seção inteira não aparece no site.
   */
  historia?: {
    titulo?: string | null;
    /**
     * Só o ano. Aparece em destaque ao lado do texto.
     */
    desde?: string | null;
    texto?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    imagem?: (number | null) | Media;
  };
  equipeTitulo?: string | null;
  equipeTexto?: string | null;
  /**
   * PENDENTE — cadastre só pessoas reais, com o nome como elas querem ser chamadas. Enquanto estiver vazio, a seção não aparece no site.
   */
  equipe?:
    | {
        nome: string;
        funcao?: string | null;
        /**
         * Opcional. Sem foto, aparecem as iniciais do nome.
         */
        foto?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  metodo?: {
    chapeu?: string | null;
    titulo?: string | null;
    /**
     * Numerados na ordem em que estiverem aqui — arraste para reordenar. Deixe vazio para esconder a seção.
     */
    passos?:
      | {
          titulo: string;
          texto?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Bloco final da página, que leva para o orçamento.
   */
  fechamento?: {
    titulo?: string | null;
    texto?: string | null;
    ctaTexto?: string | null;
    ctaLink?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Página "Localização" do site. Preencha só o que for verdade — o que ficar vazio some da página.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "localizacao".
 */
export interface Localizacao {
  id: number;
  chapeu?: string | null;
  /**
   * Depois de preencher o endereço, vale reescrever este título falando da visita — algo como "Do asfalto da BR até a nossa porta".
   */
  titulo: string;
  /**
   * Com o endereço e os horários publicados, troque por um texto que convide o cliente a vir até a base.
   */
  lead?: string | null;
  /**
   * Primeira etapa do roteiro. Onde a LM atende, mesmo longe da sede.
   */
  regiao?: string | null;
  /**
   * O endereço da sede. Sem logradouro e cidade preenchidos, o mapa e a rota não aparecem no site.
   */
  endereco?: {
    logradouro?: string | null;
    numero?: string | null;
    complemento?: string | null;
    bairro?: string | null;
    cidade?: string | null;
    estado?: string | null;
    cep?: string | null;
  };
  /**
   * Como quem nunca veio reconhece o lugar: o que tem na esquina, de que lado da pista, o que aparece antes.
   */
  referencia?: string | null;
  /**
   * Opcional. Cole o link do Google Maps da LM se quiser fixar o ponto exato. Vazio, o mapa é montado a partir do endereço acima.
   */
  mapaUrl?: string | null;
  /**
   * Deixe vazio se ainda não quiser publicar horário.
   */
  horarios?:
    | {
        dias: string;
        horario: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Opcional, mas ajuda muito: é por ela que o cliente reconhece o lugar na rua.
   */
  imagem?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  secaoCatalogo?:
    | T
    | {
        chapeu?: T;
        titulo?: T;
        texto?: T;
      };
  bannersHero?:
    | T
    | {
        imagem?: T;
        alt?: T;
        link?: T;
        id?: T;
      };
  bannersFaixa1?:
    | T
    | {
        imagem?: T;
        alt?: T;
        link?: T;
        id?: T;
      };
  bannersFaixa2?:
    | T
    | {
        imagem?: T;
        alt?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sobre_select".
 */
export interface SobreSelect<T extends boolean = true> {
  chapeu?: T;
  titulo?: T;
  lead?: T;
  ctaTexto?: T;
  ctaLink?: T;
  imagem?: T;
  imagemLegenda?: T;
  ficha?:
    | T
    | {
        rotulo?: T;
        valor?: T;
        id?: T;
      };
  capacidadesChapeu?: T;
  capacidadesTitulo?: T;
  capacidadesTexto?: T;
  capacidades?:
    | T
    | {
        titulo?: T;
        texto?: T;
        id?: T;
      };
  projetos?:
    | T
    | {
        chapeu?: T;
        titulo?: T;
        ctaTexto?: T;
        ctaLink?: T;
      };
  historia?:
    | T
    | {
        titulo?: T;
        desde?: T;
        texto?: T;
        imagem?: T;
      };
  equipeTitulo?: T;
  equipeTexto?: T;
  equipe?:
    | T
    | {
        nome?: T;
        funcao?: T;
        foto?: T;
        id?: T;
      };
  metodo?:
    | T
    | {
        chapeu?: T;
        titulo?: T;
        passos?:
          | T
          | {
              titulo?: T;
              texto?: T;
              id?: T;
            };
      };
  fechamento?:
    | T
    | {
        titulo?: T;
        texto?: T;
        ctaTexto?: T;
        ctaLink?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "localizacao_select".
 */
export interface LocalizacaoSelect<T extends boolean = true> {
  chapeu?: T;
  titulo?: T;
  lead?: T;
  regiao?: T;
  endereco?:
    | T
    | {
        logradouro?: T;
        numero?: T;
        complemento?: T;
        bairro?: T;
        cidade?: T;
        estado?: T;
        cep?: T;
      };
  referencia?: T;
  mapaUrl?: T;
  horarios?:
    | T
    | {
        dias?: T;
        horario?: T;
        id?: T;
      };
  imagem?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}